### ISSUE TITLE
#include <stdlib.h> missing

### ISSUE THREAD

**Issue by tomboulier** [paulgribble/CBootCamp#5]
In chapter 6, section **Variable-Length Arrays**, the first piece of code misses ```#include <stdlib.h>``` header declaration. Indeed, otherwise I get the error message *"attention : implicit declaration of function ‘atoi’*

**Comment by paulgribble** [comment]
great! thank you for spotting that. it's fixed now. -Paul

**Comment by tomboulier** [comment]
No problem. This online course is really great, thank you in return. I have a couple of other little typos I can raise if you wish.

**Comment by paulgribble** [comment]
sure that would be great
